// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw4mX2MwkEXbXbnL6ssUQsc2zn3-JOopQ',
    appId: '1:874599959250:web:4b0dfb9e70e3f62bda3b0b',
    messagingSenderId: '874599959250',
    projectId: 'financefriend-41da9',
    authDomain: 'financefriend-41da9.firebaseapp.com',
    storageBucket: 'financefriend-41da9.appspot.com',
    measurementId: 'G-9X90S5E8XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsHm6t7kFs6fr3ymTZSe0Mf_ypCss1jLg',
    appId: '1:874599959250:android:b3c0815e0964e664da3b0b',
    messagingSenderId: '874599959250',
    projectId: 'financefriend-41da9',
    storageBucket: 'financefriend-41da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSDUSNpVT1QKFNcbwGQPpZr-2F7_RVVwU',
    appId: '1:874599959250:ios:dd1d867eb4fdefe6da3b0b',
    messagingSenderId: '874599959250',
    projectId: 'financefriend-41da9',
    storageBucket: 'financefriend-41da9.appspot.com',
    iosClientId: '874599959250-imoq3bqq1l3tgt4ol00fcbh84hud1ljd.apps.googleusercontent.com',
    iosBundleId: 'com.example.financefriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSDUSNpVT1QKFNcbwGQPpZr-2F7_RVVwU',
    appId: '1:874599959250:ios:2cd40113ac62666dda3b0b',
    messagingSenderId: '874599959250',
    projectId: 'financefriend-41da9',
    storageBucket: 'financefriend-41da9.appspot.com',
    iosClientId: '874599959250-0uja5hmtspn9hc14tnftp869hd3kddeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.financefriend.RunnerTests',
  );
}